"use client";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout, FloatButton } from 'antd'
import AppSider from '@/components/AppSider';
import AppHeader from '@/components/AppHeader';
import AppFooter from '@/components/AppFooter';
import LHeader from '@/components/LHeader';
import LFooter from '@/components/LFooter';


const { Header, Content, Sider, Footer } = Layout

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
    return (
        <Layout className='main-container'>
            <Header style={{padding: '0 10px'}}>
                <AppHeader />
            </Header>
            <Layout>
                <AppSider />
                <Content>
                    {children}
                </Content>
            </Layout>
            
        </Layout>
    )
}
