"use client";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { Layout, FloatButton } from 'antd'
import { ArrowLeftOutlined } from '@ant-design/icons'
import LHeader from '@/components/LHeader';
import LFooter from '@/components/LFooter';




const { Header, Content, Sider, Footer } = Layout

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
    return (

        <Layout className='main-container' style={{
            background: '#fff'
        }}>

            <Header style={{ margin: '8px' }}>
                <LHeader />
            </Header>
            <Content style={{
                background: '#fff', display: 'flex',
                justifyContent: 'center',
                alignItems: 'center',
                flexWrap: 'wrap',
                overflow: 'auto',
            }}>
                {children}
            </Content>
            <Footer style={{ padding: 0, }}>
                <LFooter />
            </Footer>
        </Layout>

    )
}
